### ISSUE TITLE
Control board - Reset of the A4988 driver

### ISSUE THREAD

**Issue by tillethz** [pulp-bio/dopflow#4]
The reset of the A4988 driver (D1_RESET line) is connected to pin 61 of the STM32 discovery board which is used by another sensor. this prevents the Driver from working. 
Please connect the D1_RESET line to the nrst pin of the STM32 discovery board (pin 4). That way you don't need a jumper wire from X29 to nrst and can add a simple jumper between X29 and X28.

<img width="392" alt="image" src="https://github.com/user-attachments/assets/767f19d6-944a-4f96-8294-dd2a643ee4ec">

**Comment by Sergio5714** [comment]
Fixed
